### ISSUE TITLE
Un-private (->privatewrite) variables in XComPathingPawn

### ISSUE THREAD

**Issue by Soldier9** [X2CommunityCore/X2CommunityHighlander#220] opened 2017-04-02 19:49 UTC
Allow mods to get more information about the currently previewed movement path. I'm especially interested in the following for use in Gotcha Again:
var private bool WaypointModifyMode; // toggle set by ui to show waypoint add/remove markers. doesn't change behavior, just looks
var private array<HazardMarker>					    HazardMarkers; // all tiles with a hazard on them
var private array<TTile>					    	NoiseMarkers; // all tiles with a noise marker on them
var private array<TTile>						    ConcealmentMarkers; // all tiles with a concealment marker on them

**Comment by robojumper** [comment] 2017-04-02 19:50
Maybe we can make them protectedwrite rather, to allow overrides if neccessary.

**Comment by Soldier9** [comment] 2017-04-04 05:07
As long as they're anything but private I am happy, but protectedwrite is probably better since it allows for overrides.

**Comment by robojumper** [comment] 2017-05-28 16:51
Duplicate of #259, resolved by LW1.3 patch.

**Closed by robojumper** 2017-05-28 16:51 UTC
